name: CI/CD Docker Build & Deploy

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: cobalt-alcove-345208
  GCP_REGION: us-central1
  SERVICE_NAME: webapp-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK 17 + Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 3️⃣ Build & Test
      - name: Build with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test

      # 4️⃣ Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 5️⃣ Install gcloud SDK
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}

      # 6️⃣ Configure Docker for Artifact Registry
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      # 7️⃣ Set IMAGE env variable (dynamic)
      - name: Set IMAGE name
        run: echo "IMAGE=${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/webapp-repo/webapp:${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      # 8️⃣ Build & Push Docker Image
      - name: Build and Push Image
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE

      # 9️⃣ Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $GCP_REGION \
            --platform managed \
            --allow-unauthenticated
